language: node_js
node_js:
 - "6"
 - "8"
 - "10"
 - "node"
env:
 - DEFAULT_NODE_VERSION=10
addons:
  apt:
    sources:
    - boost-latest
    packages:
    # for SWObjects
    - libboost-all-dev
    - uuid-dev
before_script:
  - | # Build SWObjects for spec tests
    if [ ! -e swobjects/bin/sparql ]; then
      rm -rf swobjects
      git clone https://github.com/ericprud/SWObjects.git swobjects
      pushd swobjects
      git checkout 1739b95536d2b7bf516f5543a6cf7e5c46a9a4f9
      sed -i 's/^SQL_CLIENTS=.*/SQL_CLIENTS= MYSQL /' CONFIG
      sed -i 's/^CRYPTLIB=.*/LDFLAGS += -lltdl -ldl/' CONFIG
      make -j2 bin/sparql
      popd
    fi
  - PATH=$PATH:swobjects/bin
  - sparql -v
script:
  - npm run lint
  - npm test
  - npm run spec
  - npm run docs
after_success:
  - if [ "$TRAVIS_NODE_VERSION" == "$DEFAULT_NODE_VERSION" ]; then
      npm install coveralls;
      node_modules/.bin/nyc --reporter=text-lcov mocha |
        node_modules/.bin/coveralls;
      ./.travis_build_pages;
    fi
cache:
  apt: true
  directories:
    - node_modules
    - swobjects
    - spec/turtle
    - spec/trig
sudo: false
